config/routes.rb
Rails.application.routes.draw do

	get 'top' => 'lists#top'
	root :to => 'lists#top'

  # get 'todolists/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'top' => 'home#top'

  resources :lists
  # post 'todolists' => 'todolists#create'

  # get 'todolists' => 'todolists#index'
  # get 'todolists/:id' => 'todolists#show', as: 'todolist'
  # get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  # patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
  # delete 'todolists/:id' => 'todolists#destroy', as: 'destroy_todolist'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def top
  end

  def create
  	@list = List.new(list_params)
   if @list.save
 	# flash[:notice] = 'successfully create'
  	redirect_to list_path(@list), notice: 'successfully create'
   else
   	@lists = List.all
       render action: :index
   end
  end

  def index
  	@lists = List.all
    @list = List.new
  end

  def show
  	@list = List.find(params[:id])
  end

  def edit
  	@list = List.find(params[:id])
  end

  def update
  	@list = List.find(params[:id])
   if @list.update(list_params)
  	redirect_to list_path(@list.id), notice: 'successfully update'
   else
   	render action: :edit
   end
  end

  def destroy
  	list = List.find(params[:id])
  	list.destroy
  	redirect_to lists_path

  end


  private
  def list_params
  	params.require(:list).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>ここはTopページです</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Editing Book</h1>
<!-- form_for部分 -->
<%= form_for(@list) do |f| %>

<% if @list.errors.any? %>
<h3><%= @list.errors.count %> errors prohibited this book from being saved</h3>

    <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

<% end %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Update Book' %>
  <br>

  <%=link_to "show",list_path(@list) %>
  |
  <%=link_to "Back",lists_path %>

<% end %>

app/views/lists/index.html.erb
<h1>Books</h1>


<table>
<thead>
  <tr>
    <th>title</th> <th>body</th> <th colspan="3"></th>
  </tr>
</thead>

<tbody>
	<% @lists.each do |list| %>
  <tr>
    <td><%= list.title %></td>
    <td><%= list.body %></td>
    <td><%=link_to "Show",list_path(list.id) %></td>
    <td> <%=link_to "Edit",edit_list_path(list.id) %></td>
    <td><%=link_to "Destroy",list_path(list.id), method: :delete, "data-confirm" => "Are you sure?" %>

    </td>
  </tr>
<% end %>
</tbody>

</table>


<!-- この下に投稿画面 -->
<h3>New book</h3>
<%= form_for(@list) do |f| %>
<!-- エラーのところ -->
<% if @list.errors.any? %>
<h3><%= @list.errors.count %> errors prohibited this book from being saved</h3>
    <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

<% end %>


<h4>Title</h4>
<%= f.text_field :title %>
<h4>Body</h4>
<%= f.text_area :body %>
<br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/lists/show.html.erb
<!-- サクセスメッセージ -->
<p id="notice">
	<%= notice %>
</p>

<p><strong>title:</strong><%= @list.title %></p>
<p><strong>body:</strong><%= @list.body %></p>

<!-- 未定 -->
<%=link_to "Edit",edit_list_path(@list) %>
|
<%=link_to "Back",lists_path %>

app/views/lists/top.html.erb
<h1>ようこそ　Bookersへ！</h1>
<p>Bookers　では　さまざまな書籍に関するあなたの意見や</p><Br>
<p>印象を共有し交換することができます</p><br>
<br>
<%=link_to "start",lists_path %>